// Code generated by oak. DO NOT EDIT.
package main

import "log/slog"

// LogValue implements slog.LogValuer for Example
func (e Example) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Int64("IntValue", int64(e.IntValue)),
		slog.String("StringValue", "[REDACTED]"),
		slog.Float64("FloatValue", e.FloatValue),
		slog.Any("NestedValue", e.NestedValue),
	)
}

// LogValue implements slog.LogValuer for NestedExample
func (n NestedExample) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("BoolValue", "[REDACTED]"),
		slog.Any("SliceValue", n.SliceValue),
		func() slog.Attr {
			if n.PointerValue == nil {
				return slog.String("PointerValue", "null")
			}
			return slog.String("PointerValue", *n.PointerValue)
		}(),
	)
}
